using System;
using System.Collections;
using System.Collections.Generic;
using Unity.VisualScripting;
using UnityEditor;
using UnityEngine;
using UnityEngine.EventSystems;

public class HTiles : MonoBehaviour , IDragHandler , IPointerClickHandler
{
    private TerrainType _terrainType;

    public TerrainType terrainType
    {
        get { return _terrainType; }
        set
        {
            _terrainType = value;
            Renderer renderer = gameObject.GetComponent<Renderer>();
            
            switch (_terrainType)
            {
                case TerrainType.Ground:
                    //Test Renderer
                    renderer.material.color = Color.white;
                    break;
                case TerrainType.Water:
                    renderer.material.color = Color.blue;
                    break;
                case TerrainType.Bridge:
                    //renderer.material.color = Color.white;
                    break;
            }
        }
    }
    
    public SOTile tile;
    public HTileList tileList; //í”„ë¼ì´ë²³?

    [HideInInspector] public float noiseValue;
    [HideInInspector] public float cellSize = 1;
    private IPointerEnterHandler pointerEnterHandlerImplementation;

    private bool canSet = false;

    private void Start()
    {
        //ê²Œì„ë§¤ë‹ˆì €ì•ˆì˜ UIë§¤ë‹ˆì € ì•ˆì˜ íƒ€ì¼ë¦¬ìŠ¤íŠ¸ê°€ ìˆì„ê²ƒì„
        //íƒ€ì¼ë¦¬ìŠ¤íŠ¸ì™€ ì—°ê²°í•´ì¤Œ
    }

    void OnMouseOver()
    {

        if (RangeCheck(MousePosition(), transform.position))
        {
            Debug.Log(transform.position);
            canSet = true;
        }
    }
    
    public void OnPointerClick(PointerEventData eventData)
    {
        if (canSet)
        {
            switch (eventData.button)
            {
                case PointerEventData.InputButton.Left:
                    SetTile();
                    break;
                case PointerEventData.InputButton.Right:
                    Debug.Log("ğŸ–±ï¸ ì˜¤ë¥¸ìª½ ë²„íŠ¼ í´ë¦­!");
                    break;
            }
        }
    }
    
    public void OnDrag(PointerEventData eventData)
    {
        if (canSet)
        {
            
        }
    }
    public void SetTile()
    {
        if(tileList.currentHWayType == HWayType.None) return;
        
        this.tile = tileList.soTiles[(int)tileList.currentHWayType];
        //í•¨ìˆ˜ ì•ˆì— ë§Œë“¤ê±´ë°
        //ìƒˆë¡œ ì˜¤ë¸Œì íŠ¸ë¥¼ ìƒì„±í•˜ëŠ”ê²ƒì´ ì•„ë‹ˆê³ 
        //ê¸°ì¡´ íƒ€ì¼ì—ì„œ ë§ì”Œìš¸ê²ƒì„
    }

    public void DestroyTile()
    {
        //this.tile = 
    }
    
    Vector3 MousePosition()
    {
        Ray ray = Camera.main.ScreenPointToRay(Input.mousePosition);
        RaycastHit hit;
        if (Physics.Raycast(ray, out hit))
        {
            return hit.point;
        }
        return Vector3.zero;
    }

    bool RangeCheck(Vector2 point, Vector2 center)
    {
        return (point.x - center.x) * (point.x - center.x) + 
            (point.y - center.y) * (point.y - center.y) <= cellSize * .2f;
    }

    void OnDrawGizmos()
    {
        Gizmos.color = Color.green;
        Gizmos.DrawWireSphere(transform.position , cellSize* .2f);
    }

}
